### ISSUE TITLE
Kindle file build fails

### ISSUE THREAD

**Issue by Roboe** [daniel-j/epubmake#1]
First of all: awesome work! I discovered this yesterday and you made my day.

This is an informative, low-priority issue. I was just testing your work with a simple ebook I did time ago, and this came up:

```
$ make buildkindle
Downloading kindlegen...
####################################################################################### 100,0%
Building Kindle file...
/bin/sh: 1: cd: can't cd to tmp/./src/
Makefile:65: recipe for target 'build/ebook.mobi' failed
make: *** [build/ebook.mobi] Error 2
```
(Debian Testing "Buster")

Seems to be something with the path. Kinda weird, because `make buildkepub` do similar things and it works.

**Comment by Roboe** [comment]
It turned out that it couldn't `cd` because there is no dir to change if `PNGFILES` is empty. I've fixed it with a `ifndef`. PR in the making.

**Comment by daniel-j** [comment]
Hey, glad you like my epubmake :)
The ebooks I exported for Kindle all had png images heh, I didn't test one that hadn't! I looked at your PR and found that `ifndef PNGFILES` doesn't fix the issue, since it causes the png conversion code to never be run even though there are png files! Please change it to `ifneq ($(PNGFILES),)` and I'll merge it! Nice find!

**Comment by Roboe** [comment]
Aaah, ~~good~~ old make syntax, haha. Fixed!

**Comment by daniel-j** [comment]
I did some cleaning to the Makefile and added a `buildazw3` target (uses Calibre's ebook-convert). Please try that as well if you want. Don't use it if you're publishing ebooks on Amazon though. https://github.com/daniel-j/epubmake/commit/17be4e18f8b29bda3d14396a21ba4ec95ef22efb

**Comment by Roboe** [comment]
Thanks, I already tried it back when you pushed it. It works (as in it successfully outputs a `ebook.azw3` file), but I don't have a Kindle to test. I guess Calibre does its work just well.

> Don't use it if you're publishing ebooks on Amazon though.

Thank you for the warning, but I'm not. [Ethics](https://www.defectivebydesign.org/amazon). However, it comes handly to generate a `awz3` file for those users that &mdash;unfortunately&mdash; bought a device that doesn't support reading the standard file format for e-books.
